gerenciamento-de-atividades/config/routes.rb
Rails.application.routes.draw do
  resources :subatividades
  resources :activities

  root 'activities#index'
  get 'index' => 'activities#index', :as => 'home'

end

gerenciamento-de-atividades/app/models/subatividade.rb
class Subatividade < ActiveRecord::Base
	validates :name, length: { maximum: 100, too_long: "O nome deve ter no máximo %{count} caracteres"}
	validates_presence_of :name, message: "O nome não pode ser vazio"
	validates_presence_of :description, message: "A descrição não pode ser vazia"
	validates :description, length: { maximum: 500, too_long: "A descrição deve ter no máximo %{count} caracteres" }
	validates_inclusion_of :duration, :in => 0..200, message: "Por favor selecione um valor de 0 a 200"
	validates_presence_of :location, message: "Por favor, selecione a localizalização da atividade"
	validates_presence_of :progress, message: "Por favor, selecione o andamento da atividade"

end

gerenciamento-de-atividades/app/controllers/subatividades_controller.rb
class SubatividadesController < ApplicationController
  before_action :set_subatividade, only: [:show, :edit, :update, :destroy]

  # GET /subatividades
  # GET /subatividades.json
  def index
    @subatividades = Subatividade.all
  end

  # GET /subatividades/1
  # GET /subatividades/1.json
  def show
  end

  # GET /subatividades/new
  def new
   # activity = Activity.find(params[:activity_id])
    @subatividade = Subatividade.new
    @activity_id = params[:activity_id]
    puts "olar"*20
    puts params[:activity_id]
    puts "olar"*20
  end

  # GET /subatividades/1/edit
  def edit
  end

  # POST /subatividades
  # POST /subatividades.json
  def create
    @subatividade = Subatividade.new(subatividade_params)
    @subatividade.activity_id = session[:activity_id]
    puts "&"*80
    puts @subatividade.activity_id
    puts "&"*80
    #@subatividade = current_activity.subatividades.build(params[:subatividade])

    respond_to do |format|
      if @subatividade.save
        format.html { redirect_to @subatividade, notice: 'Subatividade was successfully created.' }
        format.json { render :show, status: :created, location: @subatividade }
      else
        format.html { render :new }
        format.json { render json: @subatividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subatividades/1
  # PATCH/PUT /subatividades/1.json
  def update
    respond_to do |format|
      if @subatividade.update(subatividade_params)
        format.html { redirect_to @subatividade, notice: 'Subatividade was successfully updated.' }
        format.json { render :show, status: :ok, location: @subatividade }
      else
        format.html { render :edit }
        format.json { render json: @subatividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subatividades/1
  # DELETE /subatividades/1.json
  def destroy
    @subatividade.destroy
    respond_to do |format|
      format.html { redirect_to subatividades_url, notice: 'Subatividade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subatividade
      @subatividade = Subatividade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subatividade_params
      params.require(:subatividade).permit(:name, :description, :duration, :location, :progress)
    end
end

gerenciamento-de-atividades/app/helpers/subatividades_helper.rb
module SubatividadesHelper
end

gerenciamento-de-atividades/app/views/subatividades/_form.html.erb
<%= bootstrap_form_for @subatividade, :html => { :class => "form-horizontal activity" } do |f| %>
  
  <div class="col-md-6">
    <%= f.text_field :name, label: "Nome da Subatividade" %>
    <%= f.text_area :description, label: "Descrição da Subatividade" %>
    <%= f.number_field :duration, min: 0, max: 200, label: "Duração da Subatividade (em horas)" %>
    <%= f.form_group :location, label: { text: "Localização" } do  %>
      <%= f.radio_button :location,"Presencial", label: "Presencial" %>
      <%= f.radio_button :location,"Não presencial", label: "Não presencial"%>
    <% end %>
    <%= f.form_group :progress, label: { text: "Andamento" } do  %>
      <%= f.radio_button :progress,"A começar", label: "A começar" %>
      <%= f.radio_button :progress,"Em execução", label: "Em execução"%>
      <%= f.radio_button :progress,"Terminada", label: "Terminada"%>
    <% end %>
    <%= f.submit "Salvar", class: "btn btn-success" %>
    <%= f.button "Limpar Formulário", type: :resset, class: "btn btn-default" %>
    <%= link_to 'Voltar', subatividades_path , class: "btn btn-default" %>
  </div>
<% end %>

gerenciamento-de-atividades/app/views/subatividades/edit.html.erb
<%- model_class = Subatividade -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

gerenciamento-de-atividades/app/views/subatividades/index.html.erb
<%- model_class = Subatividade -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:progress) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subatividades.each do |subatividade| %>
      <tr>
        <td><%= link_to subatividade.id, subatividade_path(subatividade) %></td>
        <td><%= subatividade.name %></td>
        <td><%= subatividade.description %></td>
        <td><%= subatividade.duration %></td>
        <td><%= subatividade.location %></td>
        <td><%= subatividade.progress %></td>
        <td><%=l subatividade.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subatividade_path(subatividade), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subatividade_path(subatividade),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subatividade_path,
            :class => 'btn btn-primary' %>

gerenciamento-de-atividades/app/views/subatividades/new.html.erb
<%- model_class = Subatividade -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

gerenciamento-de-atividades/app/views/subatividades/show.html.erb
<%- model_class = Subatividade -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @subatividade.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @subatividade.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @subatividade.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @subatividade.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:progress) %>:</strong></dt>
  <dd><%= @subatividade.progress %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              subatividades_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subatividade_path(@subatividade), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subatividade_path(@subatividade),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>