gerenciamento-de-atividades/config/routes.rb
Rails.application.routes.draw do
  resources :subatividades
  resources :activities

  root 'activities#index'
  get 'index' => 'activities#index', :as => 'home'

end

gerenciamento-de-atividades/app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many :subatividades

	validates :name, length: { maximum: 100, too_long: "O nome deve ter no máximo %{count} caracteres"}
	validates_presence_of :name, message: "O nome não pode ser vazio"
	validates_presence_of :description, message: "A descrição não pode ser vazia"
	validates :description, length: { maximum: 500, too_long: "A descrição deve ter no máximo %{count} caracteres" }
	validates_presence_of :activity_type, message: "Por favor, selecione o tipo da atividade"

	def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	end
end

gerenciamento-de-atividades/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
     @activities = Activity.all
      if params[:search]
        @activities = Activity.search(params[:search]).order("created_at DESC")
      else
        @activities = Activity.all.order('created_at DESC')
      end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    #@subatividades = @activity.subatividades

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description, :activity_type)
    end
end

gerenciamento-de-atividades/app/helpers/activities_helper.rb
module ActivitiesHelper
end

gerenciamento-de-atividades/app/views/activities/_form.html.erb
<%= bootstrap_form_for @activity, :html => { :class => "form-horizontal activity" } do |f| %>
  <div class="col-md-6">
    <%= f.text_field :name, label: "Nome da Atividade" %>
    <%= f.text_area :description, label: "Descrição da Atividade" %>
    <%= f.form_group :activity_type, label: { text: "Tipo" } do %>
        <%= f.radio_button :activity_type, "Consultoria", label: "Consultoria" %>
        <%= f.radio_button :activity_type, "Administrativa", label: "Administrativa" %>
    <% end %>
    <%= f.submit "Salvar", class: "btn btn-success" %>
    <%= f.button "Limpar Formulário", type: :reset, class: "btn btn-default" %>
    <%= link_to 'Voltar', activities_path , class: "btn btn-default" %>
  </div>
<% end %>

gerenciamento-de-atividades/app/views/activities/edit.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h2>Editar Atividade</h2>
</div>
<%= render :partial => 'form' %>

gerenciamento-de-atividades/app/views/activities/index.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1>Atividades</h1>
</div>
<%= form_tag(activities_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Buscar atividades", class: 'search-bar' %>
  <%= submit_tag "Buscar", class: 'btn btn-default' %>
  <br><br>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name("Nome") %></th>
      <th><%= model_class.human_attribute_name("Descrição") %></th>
      <th><%= model_class.human_attribute_name("Tipo da atividade") %></th>
      <th><%= model_class.human_attribute_name("Data de Criação") %></th>
      <th><%=t '.actions', :default => t("Ações") %></th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= link_to activity.id, activity_path(activity) %></td>
        <td><%= activity.name %></td>
        <td><%= activity.description %></td>
        <td><%= activity.activity_type %></td>
        <td><%=l activity.created_at %></td>
        <td>
          <%= link_to t('.new', :default => t("Adicionar Subatividade")),
                      new_subatividade_path, :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("Ver Subatividades")),
                      edit_activity_path(activity), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("Editar")),
                      edit_activity_path(activity), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("Deletar")),
                      activity_path(activity),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("Criar nova atividade")),
            new_activity_path,
            :class => 'btn btn-success' %>

gerenciamento-de-atividades/app/views/activities/new.html.erb
<%- model_class = Activity -%>
<div class="page-header">
   <h2>Registrar nova atividade</h2>
</div>
<%= render :partial => 'form' %>

gerenciamento-de-atividades/app/views/activities/show.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @activity.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @activity.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @activity.activity_type %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              activities_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_activity_path(@activity), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              activity_path(@activity),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>